export const allServices = [
  { titleKey: 'cleaning', category: 'cleaning', price: '150 zł', duration: '45 min' },
  { titleKey: 'massage', category: 'massage', price: '100 zł', duration: '30 min' },
  { titleKey: 'biorevitalization', category: 'injection', price: '250 zł', duration: '50 min' },
  { titleKey: 'browsLashes', category: 'other', price: '120 zł', duration: '40 min' },
  { titleKey: 'mandelicPeeling', category: 'cleaning', price: '160 zł', duration: '45 min' },
  { titleKey: 'ultrasound', category: 'cleaning', price: '140 zł', duration: '40 min' },
  { titleKey: 'mesotherapy', category: 'injection', price: '220 zł', duration: '50 min' },
  { titleKey: 'problemSkin', category: 'cleaning', price: '180 zł', duration: '60 min' },
  { titleKey: 'acneTherapy', category: 'cleaning', price: '190 zł', duration: '55 min' },
  { titleKey: 'spaFace', category: 'massage', price: '200 zł', duration: '60 min' },
  { titleKey: 'lipFilling', category: 'injection', price: '350 zł', duration: '45 min' },
  { titleKey: 'botox', category: 'injection', price: '450 zł', duration: '30 min' },
  { titleKey: 'faceMask', category: 'cleaning', price: '130 zł', duration: '30 min' },
  { titleKey: 'bodyMassage', category: 'massage', price: '180 zł', duration: '60 min' },
  { titleKey: 'neckMassage', category: 'massage', price: '90 zł', duration: '25 min' },
  { titleKey: 'chemicalPeeling', category: 'cleaning', price: '210 zł', duration: '50 min' },
  { titleKey: 'microneedling', category: 'injection', price: '300 zł', duration: '60 min' },
  { titleKey: 'vitaminC', category: 'injection', price: '270 zł', duration: '45 min' },
  { titleKey: 'oxygenTherapy', category: 'massage', price: '160 zł', duration: '40 min' },
  { titleKey: 'hyaluronicMask', category: 'cleaning', price: '140 zł', duration: '35 min' },
];
